<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <UseWindowsForms>true</UseWindowsForms>
    <OutputType>Library</OutputType>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <SolutionDir Condition="$(SolutionDir) == '' Or $(SolutionDir) == '*Undefined*'">..\</SolutionDir>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="AxInterop.Microsoft.Office.Interop.OutlookViewCtl">
      <HintPath>..\ReferencedDLLs\AxInterop.Microsoft.Office.Interop.OutlookViewCtl.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Office.Interop.Outlook">
      <HintPath>..\ReferencedDLLs\Microsoft.Office.Interop.Outlook.dll</HintPath>
      <SpecificVersion>False</SpecificVersion>
      <EmbedInteropTypes>True</EmbedInteropTypes>
    </Reference>
    <Reference Include="Microsoft.Office.Interop.OutlookViewCtl">
      <HintPath>..\ReferencedDLLs\Microsoft.Office.Interop.OutlookViewCtl.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Content Include="NLog.config">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\OotDScheduledTaskDefinition.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <Content Include="Resources\Icons\AppIcon.ico" />
    <Content Include="Resources\Icons\notifyIcon.ico" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MACTrackBarLib\MACTrackBarLib\MACTrackBarLib.csproj" />
    <ProjectReference Include="..\NetSparkle\NetSparkle\NetSparkle.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="NLog" />
    <PackageReference Include="NLog.Schema" />
    <PackageReference Include="TaskScheduler" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
</Project>