<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <PlatformTarget>x64</PlatformTarget>
    <StartupObject>OotD.Program</StartupObject>
    <ApplicationManifest>..\OotD.Core\app.manifest</ApplicationManifest>
    <ApplicationIcon>..\OotD.Core\Resources\Icons\AppIcon.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\OotD.Core\OotD.Core.csproj" />
  </ItemGroup>
</Project>
