//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Drawing;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace OutlookDesktop.Properties {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class Resources {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("OutlookDesktop.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static Icon _1 {
            get {
                object obj = ResourceManager.GetObject("_1", resourceCulture);
                return ((Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static Icon _10 {
            get {
                object obj = ResourceManager.GetObject("_10", resourceCulture);
                return ((Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static Icon _11 {
            get {
                object obj = ResourceManager.GetObject("_11", resourceCulture);
                return ((Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static Icon _12 {
            get {
                object obj = ResourceManager.GetObject("_12", resourceCulture);
                return ((Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static Icon _13 {
            get {
                object obj = ResourceManager.GetObject("_13", resourceCulture);
                return ((Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static Icon _14 {
            get {
                object obj = ResourceManager.GetObject("_14", resourceCulture);
                return ((Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static Icon _15 {
            get {
                object obj = ResourceManager.GetObject("_15", resourceCulture);
                return ((Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static Icon _16 {
            get {
                object obj = ResourceManager.GetObject("_16", resourceCulture);
                return ((Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static Icon _17 {
            get {
                object obj = ResourceManager.GetObject("_17", resourceCulture);
                return ((Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static Icon _18 {
            get {
                object obj = ResourceManager.GetObject("_18", resourceCulture);
                return ((Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static Icon _19 {
            get {
                object obj = ResourceManager.GetObject("_19", resourceCulture);
                return ((Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static Icon _2 {
            get {
                object obj = ResourceManager.GetObject("_2", resourceCulture);
                return ((Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static Icon _20 {
            get {
                object obj = ResourceManager.GetObject("_20", resourceCulture);
                return ((Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static Icon _21 {
            get {
                object obj = ResourceManager.GetObject("_21", resourceCulture);
                return ((Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static Icon _22 {
            get {
                object obj = ResourceManager.GetObject("_22", resourceCulture);
                return ((Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static Icon _23 {
            get {
                object obj = ResourceManager.GetObject("_23", resourceCulture);
                return ((Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static Icon _24 {
            get {
                object obj = ResourceManager.GetObject("_24", resourceCulture);
                return ((Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static Icon _25 {
            get {
                object obj = ResourceManager.GetObject("_25", resourceCulture);
                return ((Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static Icon _26 {
            get {
                object obj = ResourceManager.GetObject("_26", resourceCulture);
                return ((Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static Icon _27 {
            get {
                object obj = ResourceManager.GetObject("_27", resourceCulture);
                return ((Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static Icon _28 {
            get {
                object obj = ResourceManager.GetObject("_28", resourceCulture);
                return ((Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static Icon _29 {
            get {
                object obj = ResourceManager.GetObject("_29", resourceCulture);
                return ((Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static Icon _3 {
            get {
                object obj = ResourceManager.GetObject("_3", resourceCulture);
                return ((Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static Icon _30 {
            get {
                object obj = ResourceManager.GetObject("_30", resourceCulture);
                return ((Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static Icon _31 {
            get {
                object obj = ResourceManager.GetObject("_31", resourceCulture);
                return ((Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static Icon _4 {
            get {
                object obj = ResourceManager.GetObject("_4", resourceCulture);
                return ((Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static Icon _5 {
            get {
                object obj = ResourceManager.GetObject("_5", resourceCulture);
                return ((Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static Icon _6 {
            get {
                object obj = ResourceManager.GetObject("_6", resourceCulture);
                return ((Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static Icon _7 {
            get {
                object obj = ResourceManager.GetObject("_7", resourceCulture);
                return ((Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static Icon _8 {
            get {
                object obj = ResourceManager.GetObject("_8", resourceCulture);
                return ((Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static Icon _9 {
            get {
                object obj = ResourceManager.GetObject("_9", resourceCulture);
                return ((Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Outlook on the Desktop.
        /// </summary>
        internal static string AboutDialogTitle {
            get {
                return ResourceManager.GetString("AboutDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Instance.
        /// </summary>
        internal static string AddInstance {
            get {
                return ResourceManager.GetString("AddInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static Icon AppIcon {
            get {
                object obj = ResourceManager.GetObject("AppIcon", resourceCulture);
                return ((Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        internal static string Calendar {
            get {
                return ResourceManager.GetString("Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        internal static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel?.
        /// </summary>
        internal static string CancelConfirmation {
            get {
                return ResourceManager.GetString("CancelConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates.
        /// </summary>
        internal static string CheckForUpdates {
            get {
                return ResourceManager.GetString("CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string ConfirmationCaption {
            get {
                return ResourceManager.GetString("ConfirmationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        internal static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        internal static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;view type=&quot;calendar&quot;&gt;
        ///	&lt;viewname&gt;Calendar&lt;/viewname&gt;
        ///	&lt;mode&gt;0&lt;/mode&gt;
        ///&lt;/view&gt;
        ///.
        /// </summary>
        internal static string DayXML {
            get {
                return ResourceManager.GetString("DayXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Editing.
        /// </summary>
        internal static string DisableEditing {
            get {
                return ResourceManager.GetString("DisableEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Editing.
        /// </summary>
        internal static string EnableEditing {
            get {
                return ResourceManager.GetString("EnableEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outlook on the Desktop Error.
        /// </summary>
        internal static string ErrorCaption {
            get {
                return ResourceManager.GetString("ErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error initializing the application:.
        /// </summary>
        internal static string ErrorInitializingApp {
            get {
                return ResourceManager.GetString("ErrorInitializingApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not launch web site..
        /// </summary>
        internal static string ErrorLaunchingWebsite {
            get {
                return ResourceManager.GetString("ErrorLaunchingWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Saving Settings.
        /// </summary>
        internal static string ErrorSavingSettings {
            get {
                return ResourceManager.GetString("ErrorSavingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error setting the dimensions.  This usually happens after you resize your desktop.  Please try setting your preferred dimensions again..
        /// </summary>
        internal static string ErrorSettingDimensions {
            get {
                return ResourceManager.GetString("ErrorSettingDimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error changing to the folder you specified. It may not be compatible with Outlook on the Desktop..
        /// </summary>
        internal static string ErrorSettingFolder {
            get {
                return ResourceManager.GetString("ErrorSettingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error setting the opacity, default of 50% used.  Please try setting it again..
        /// </summary>
        internal static string ErrorSettingOpacity {
            get {
                return ResourceManager.GetString("ErrorSettingOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap FiveDays {
            get {
                object obj = ResourceManager.GetObject("FiveDays", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click and hold this header to move the window.
        /// </summary>
        internal static string Form_Move_Help_Message {
            get {
                return ResourceManager.GetString("Form_Move_Help_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must unlock the form before attempting to move the window..
        /// </summary>
        internal static string Form_Move_Locked_Message {
            get {
                return ResourceManager.GetString("Form_Move_Locked_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Today.
        /// </summary>
        internal static string Go_to_Today {
            get {
                return ResourceManager.GetString("Go_to_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        internal static string Hide {
            get {
                return ResourceManager.GetString("Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide All.
        /// </summary>
        internal static string HideAll {
            get {
                return ResourceManager.GetString("HideAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inbox.
        /// </summary>
        internal static string Inbox {
            get {
                return ResourceManager.GetString("Inbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It appears you are attempting to run the incorrect version of Outlook on the Desktop.
        ///
        ///If you have 64-bit Office installed please use the 64-bit Outlook on the Desktop.
        ///
        ///If you have 32-bit Office installed, please use the 32-bit Outlook on the Desktop..
        /// </summary>
        internal static string Incorrect_bittedness_of_OotD {
            get {
                return ResourceManager.GetString("Incorrect_bittedness_of_OotD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please install Microsoft Office and try again..
        /// </summary>
        internal static string InstallOutlookMsg {
            get {
                return ResourceManager.GetString("InstallOutlookMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock Position.
        /// </summary>
        internal static string LockPosition {
            get {
                return ResourceManager.GetString("LockPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Requirements.
        /// </summary>
        internal static string MissingRequirementsCapation {
            get {
                return ResourceManager.GetString("MissingRequirementsCapation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Month {
            get {
                object obj = ResourceManager.GetObject("Month", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;view type=&quot;calendar&quot;&gt;
        ///	&lt;viewname&gt;Calendar&lt;/viewname&gt;
        ///	&lt;mode&gt;2&lt;/mode&gt;
        ///&lt;/view&gt;
        ///.
        /// </summary>
        internal static string MonthXML {
            get {
                return ResourceManager.GetString("MonthXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Move_Next {
            get {
                return ResourceManager.GetString("Move_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string Move_Previous {
            get {
                return ResourceManager.GetString("Move_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Narrow.
        /// </summary>
        internal static string Narrow {
            get {
                return ResourceManager.GetString("Narrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap NewEmail {
            get {
                object obj = ResourceManager.GetObject("NewEmail", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Instance Name.
        /// </summary>
        internal static string NewInstanceName {
            get {
                return ResourceManager.GetString("NewInstanceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Next {
            get {
                object obj = ResourceManager.GetObject("Next", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This program requires Microsoft Outlook 2003 or higher..
        /// </summary>
        internal static string Office2000Requirement {
            get {
                return ResourceManager.GetString("Office2000Requirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;OK.
        /// </summary>
        internal static string OKButton {
            get {
                return ResourceManager.GetString("OKButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap OneDay {
            get {
                object obj = ResourceManager.GetObject("OneDay", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outlook on the Desktop is running.
        /// </summary>
        internal static string OotdRunning {
            get {
                return ResourceManager.GetString("OotdRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opacity:.
        /// </summary>
        internal static string Opacity {
            get {
                return ResourceManager.GetString("Opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opaque.
        /// </summary>
        internal static string Opaque {
            get {
                return ResourceManager.GetString("Opaque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap PayPal {
            get {
                object obj = ResourceManager.GetObject("PayPal", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        internal static string Preferences {
            get {
                return ResourceManager.GetString("Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outlook on the Desktop Preferences.
        /// </summary>
        internal static string PreferencesTitle {
            get {
                return ResourceManager.GetString("PreferencesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Previous {
            get {
                object obj = ResourceManager.GetObject("Previous", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outlook on the Desktop.
        /// </summary>
        internal static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outlook on the Desktop is already running..
        /// </summary>
        internal static string ProgramIsAlreadyRunning {
            get {
                return ResourceManager.GetString("ProgramIsAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already Running.
        /// </summary>
        internal static string ProgramIsAlreadyRunningCaption {
            get {
                return ResourceManager.GetString("ProgramIsAlreadyRunningCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove this instance?.
        /// </summary>
        internal static string RemoveInstanceConfirmation {
            get {
                return ResourceManager.GetString("RemoveInstanceConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right click on this icon to configure Outlook on the Desktop..
        /// </summary>
        internal static string RightClickToConfigure {
            get {
                return ResourceManager.GetString("RightClickToConfigure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Folder ....
        /// </summary>
        internal static string SelectFolder {
            get {
                return ResourceManager.GetString("SelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string Separator {
            get {
                return ResourceManager.GetString("Separator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap SevenDays {
            get {
                object obj = ResourceManager.GetObject("SevenDays", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short.
        /// </summary>
        internal static string Short {
            get {
                return ResourceManager.GetString("Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All.
        /// </summary>
        internal static string ShowAll {
            get {
                return ResourceManager.GetString("ShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start With Windows.
        /// </summary>
        internal static string StartWithWindows {
            get {
                return ResourceManager.GetString("StartWithWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tall.
        /// </summary>
        internal static string Tall {
            get {
                return ResourceManager.GetString("Tall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        internal static string Tasks {
            get {
                return ResourceManager.GetString("Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Today {
            get {
                object obj = ResourceManager.GetObject("Today", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Day View.
        /// </summary>
        internal static string Toggle_Day_View {
            get {
                return ResourceManager.GetString("Toggle_Day_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Full Week View.
        /// </summary>
        internal static string Toggle_Full_Week_View {
            get {
                return ResourceManager.GetString("Toggle_Full_Week_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Month View.
        /// </summary>
        internal static string Toggle_Month_View {
            get {
                return ResourceManager.GetString("Toggle_Month_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Work Week View.
        /// </summary>
        internal static string Toggle_Work_Week_View {
            get {
                return ResourceManager.GetString("Toggle_Work_Week_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide to change this windows transparency level.
        /// </summary>
        internal static string Transparency_Slider_Help_Message {
            get {
                return ResourceManager.GetString("Transparency_Slider_Help_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must unlock the form before attempting to change the transparency level..
        /// </summary>
        internal static string Transparency_Slider_Locked_Message {
            get {
                return ResourceManager.GetString("Transparency_Slider_Locked_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transparent.
        /// </summary>
        internal static string Transparent {
            get {
                return ResourceManager.GetString("Transparent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to set view.  Your version of Outlook may not support it..
        /// </summary>
        internal static string ViewTypeNotSupported {
            get {
                return ResourceManager.GetString("ViewTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Site.
        /// </summary>
        internal static string WebSite {
            get {
                return ResourceManager.GetString("WebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;view type=&quot;calendar&quot;&gt;
        ///	&lt;viewname&gt;Calendar&lt;/viewname&gt;
        ///	&lt;mode&gt;1&lt;/mode&gt;
        ///	&lt;showfullweek&gt;1&lt;/showfullweek&gt;
        ///	&lt;showworkweek&gt;0&lt;/showworkweek&gt;
        ///&lt;/view&gt;
        ///.
        /// </summary>
        internal static string WeekXML {
            get {
                return ResourceManager.GetString("WeekXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wide.
        /// </summary>
        internal static string Wide {
            get {
                return ResourceManager.GetString("Wide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Windows RPC Server is not available. Please wait try loading Outlook on the Desktop in a few minutes.  If you still get the same error, you may have a problem with your windows installation..
        /// </summary>
        internal static string Windows_RPC_Server_is_not_available {
            get {
                return ResourceManager.GetString("Windows_RPC_Server_is_not_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;view type=&quot;calendar&quot;&gt;
        ///	&lt;viewname&gt;Calendar&lt;/viewname&gt;
        ///	&lt;mode&gt;4&lt;/mode&gt;
        ///	&lt;showfullweek&gt;0&lt;/showfullweek&gt;
        ///  &lt;showworkweek&gt;1&lt;/showworkweek&gt;	
        ///&lt;/view&gt;.
        /// </summary>
        internal static string WorkWeekXML {
            get {
                return ResourceManager.GetString("WorkWeekXML", resourceCulture);
            }
        }
    }
}
